"""Add transaction note

Revision ID: 743334f19829
Revises: 1acadea2853a
Create Date: 2025-12-20 13:35:00.431459

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "743334f19829"
down_revision: str | None = "1acadea2853a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "note")
    # ### end Alembic commands ###
