"""add_is_active_field

Revision ID: 92211afc6a51
Revises: 
Create Date: 2025-12-15 20:03:25.871047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92211afc6a51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint('categories_name_type_user_id_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_unique_constraint('uq_category_user', 'categories', ['name', 'type', 'user_id'])
    op.alter_column('transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint('uq_category_user', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_unique_constraint('categories_name_type_user_id_key', 'categories', ['name', 'type', 'user_id'])
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
