export function getDOM() {
  return {
    screens: document.querySelectorAll(".screen"),
    backdrop: document.getElementById("backdrop"),
    home: {
      screen: document.getElementById("home-screen"),
      balanceAmount: document.getElementById("balance-amount"),
      listContainer: document.getElementById("transactions-list"),
    },
    analytics: {
      screen: document.getElementById("analytics-screen"),
      segBtnSummary: document.getElementById("seg-btn-summary"),
      segBtnCalendar: document.getElementById("seg-btn-calendar"),
      summaryPane: document.getElementById("summary-pane"),
      calendarPane: document.getElementById("calendar-pane"),
      summaryTypeFilter: document.getElementById("summary-type-filter"),
      summaryRangeFilter: document.getElementById("summary-range-filter"),
      doughnutChartCanvas: document.getElementById("doughnut-chart"),
      summaryList: document.getElementById("summary-list"),
    },
    calendar: {
      container: document.getElementById("calendar-container"),
      prevMonthBtn: document.getElementById("prev-month-btn"),
      nextMonthBtn: document.getElementById("next-month-btn"),
      monthSelect: document.getElementById("month-select"),
      yearSelect: document.getElementById("year-select"),
      summaryIncome: document.getElementById("calendar-summary-income"),
      summaryExpense: document.getElementById("calendar-summary-expense"),
      summaryNet: document.getElementById("calendar-summary-net"),
      boxIncome: document.getElementById("calendar-summary-box-income"),
      boxExpense: document.getElementById("calendar-summary-box-expense"),
      boxNet: document.getElementById("calendar-summary-box-net"),
    },
    ai: {
      screen: document.getElementById("ai-screen"),
      dateFilter: document.getElementById("ai-date-filter"),
      featuresList: document.getElementById("ai-features-list"),
      btnAdvice: document.getElementById("ai-btn-advice"),
      btnSummary: document.getElementById("ai-btn-summary"),
      btnAnomaly: document.getElementById("ai-btn-anomaly"),
      resultContainer: document.getElementById("ai-result-container"),
      resultTitle: document.getElementById("ai-result-title"),
      resultBody: document.getElementById("ai-result-body"),
      resultBackBtn: document.getElementById("ai-result-back-btn"),
    },
    settings: {
      screen: document.getElementById("settings-screen"),
      currencySelect: document.getElementById("currency-select"),
      resetDataBtn: document.getElementById("reset-data-btn"),
    },
    categories: {
      screen: document.getElementById("categories-screen"),
      backBtn: document.getElementById("categories-back-btn"),
      segBtnExpense: document.getElementById("cat-seg-btn-expense"),
      segBtnIncome: document.getElementById("cat-seg-btn-income"),
      newIconInput: document.getElementById("new-category-icon"),
      newNameInput: document.getElementById("new-category-name"),
      addBtn: document.getElementById("add-category-btn"),
      list: document.getElementById("categories-list"),
    },
    editCategory: {
      screen: document.getElementById("edit-category-screen"),
      nameInput: document.getElementById("edit-category-name"),
      iconInput: document.getElementById("edit-category-icon"),
      saveBtn: document.getElementById("save-category-changes-btn"),
      deleteBtn: document.getElementById("delete-category-permanent-btn"),
      backBtn: document.getElementById("edit-category-back-btn"),
    },
    fullForm: {
      screen: document.getElementById("full-form-screen"),
      title: document.getElementById("form-title"),
      typeWrapper: document.getElementById("form-type-wrapper"),
      typeExpense: document.getElementById("form-type-expense"),
      typeIncome: document.getElementById("form-type-income"),
      categorySelect: document.getElementById("category-select"),

      amountInput: document.getElementById("transaction-amount"),
      currencySelect: document.getElementById("form-currency-select"),
      currencyLabel: document.getElementById("form-currency-label"),

      dateInput: document.getElementById("transaction-date"),
      noteInput: document.getElementById("transaction-note"),

      saveBtn: document.getElementById("save-btn"),
      cancelBtn: document.getElementById("cancel-btn"),
      deleteBtn: document.getElementById("delete-btn"),
    },
    quickAdd: {
      screen: document.getElementById("quick-add-screen"),
      manageBtn: document.getElementById("quick-add-manage-categories-btn"),
      gridExpense: document.getElementById("quick-add-grid-expense"),
      gridIncome: document.getElementById("quick-add-grid-income"),
      manualExpense: document.getElementById("quick-manual-expense"),
      manualIncome: document.getElementById("quick-manual-income"),
    },
    daySheet: {
      sheet: document.getElementById("day-details-sheet"),
      header: document.querySelector("#day-details-sheet .sheet-header"),
      contentWrapper: document.getElementById("sheet-content-wrapper"),
      title: document.getElementById("sheet-date-title"),
      list: document.getElementById("sheet-transactions-list"),
    },
    quickModal: {
      sheet: document.getElementById("quick-add-modal-sheet"),
      header: document.querySelector("#quick-add-modal-sheet .sheet-header"),
      title: document.getElementById("quick-modal-title"),

      currencySelect: document.getElementById("quick-currency-select"),
      currencyLabel: document.getElementById("quick-currency-label"),

      amountInput: document.getElementById("quick-modal-amount"),

      noteToggleBtn: document.getElementById("quick-add-note-toggle"),
      noteInput: document.getElementById("quick-modal-note"),

      saveBtn: document.getElementById("quick-modal-save-btn"),
    },
    summarySheet: {
      sheet: document.getElementById("summary-details-sheet"),
      header: document.querySelector("#summary-details-sheet .sheet-header"),
      title: document.getElementById("summary-sheet-title"),
      currency: document.getElementById("summary-sheet-currency"),
      amountInput: document.getElementById("summary-sheet-amount"),
    },
    tabs: {
      home: document.getElementById("tab-home"),
      analytics: document.getElementById("tab-analytics"),
      add: document.getElementById("tab-add"),
      ai: document.getElementById("tab-ai"),
      settings: document.getElementById("tab-settings"),
    },
  };
}
